### ISSUE TITLE
List objects in room bug

### ISSUE THREAD

**Issue by tjr1974** [tbamud/tbamud#105]
In file **act.informative.c**, we have the **look_at_room** function, which calls the **list_obj_to_char** function to list all objects in the room. Unfortunately, this list is being constructed or displayed in reverse order. That is... the first obj in the list should appear at the top of the list, the second obj should appear second, etcetera.

However, the exact opposite occurs. The first object is displayed at the bottom of the list, the second object is just above the first, etcetera. As if, iterating through a loop/list/array in reverse.

Ordinarily, this wouldn't be an issue. However, if you're standing in a room with a fountain or message board, then any items dropped by a player are listed in the room above the board or fountain. This is not right! We can not have players, literally, moving fountains around the room.

![Screenshot from 2022-10-17 02-34-11](https://user-images.githubusercontent.com/116045172/196311578-1ea3ebdf-4b85-4891-9e55-df80116427ab.png).

**Comment by welcor** [comment]
As I wrote on the forums, I was anticipating a pull request, not an issue. However, let's engage 😊

The reason for this behavior is probably that obj_to_room() inserts at the beginning of the list: https://github.com/tbamud/tbamud/blob/master/src/handler.c#L679. This has been the default behavior since time eternal.

**Comment by welcor** [comment]
Btw this is the same everywhere we insert in lists..

**Comment by tjr1974** [comment]
Apologies for the "pull request" versus "issue". I'm not very familiar with github and how things work here. Regardless, thanks for link to the specific line of code. That's very helpful. I can work with that. 

The only MUD I've played used a heavily modified version of the CircleMUD codebase. It must have used code to reverse the display to the player. That's why the default behavior struck me as odd and incorrect.

As for other lists, I suspect the default behavior is preferable for things like inventory, objects in containers, etcetera.

**Comment by tjr1974** [comment]
Thanks to Thomas we have this solution:

/* put an object in a room */
void obj_to_room(struct obj_data *object, room_rnum room)
{
  if (!object || room == NOWHERE || room > top_of_world){
    log("SYSERR: Illegal value(s) passed to obj_to_room. (Room #%d/%d, obj %p)",
	room, top_of_world, (void *)object);
  }
	else {
	  if (world[room].contents == NULL){  // if list is empty
		  world[room].contents = object; // add object to list
    }
		else {
			struct obj_data *i = world[room].contents; // define a temporary pointer
			while (i->next_content != NULL) i = i->next_content; // find the first without a next_content
			i->next_content = object; // add object at the end
		}
	object->next_content = NULL; // mostly for sanity. should do nothing.
	IN_ROOM(object) = room
	object->carried_by = NULL;
	if (ROOM_FLAGGED(room, ROOM_HOUSE))
	  SET_BIT_AR(ROOM_FLAGS(room), ROOM_HOUSE_CRASH);
	}
}

**Comment by tjr1974** [comment]
Thanks to Thomas, we have a solution!
[obj_to_room.txt](https://github.com/tbamud/tbamud/files/9845068/obj_to_room.txt)
