### ISSUE TITLE
Zone List Documentation

### ISSUE THREAD

**Issue by tjr1974** [tbamud/tbamud#106]
A zone list should be included in either /doc or /lib/world/zone.

Zone List
0: The Builder Academy Zone (rooms 0-99).
1: Sanctus (rooms 100-199).
2: Sanctus II (rooms 200-299).
3: Sanctus III (rooms 300-399).
4: Jade Forest (rooms 400-499).
5: Newbie Farm (rooms 500-599).
6: Sea of Souls (rooms 600-699).
7: Camelot (rooms 700-799).
9: River Island of Minos (rooms 900-999).
11: Frozen Castle (rooms 1100-1199).
12: God Complex Merged with 343 (rooms 1200-1299).
13: TBA Examples (rooms 1300-1399).
14: TBA Examples II (rooms 1400-1499).
15: Straight Path (rooms 1500-1599).
16: Camelot II (rooms 1600-1699).
17: Camelot III (rooms 1700-1799).
18: Nuclear Wasteland (rooms 1800-1899).
19: Spider Swamp (rooms 1900-1999).
20: Arena (rooms 2000-2099).
22: Tower of the Undead (rooms 2200-2299).
25: High Tower of Magic (rooms 2500-2599).
26: High Tower of Magic II (rooms 2600-2699).
27: Memlin Caverns (rooms 2700-2799).
28: Mudschool (rooms 2800-2899).
30: Northern Midgaard (rooms 3000-3099).
31: Southern Midgaard (rooms 3100-3199).
32: Midgaard (rooms 3200-3299).
33: Three of Swords (rooms 3300-3399).
35: Miden'Nir (rooms 3500-3599).
36: Chessboard of Midgaard (rooms 3600-3699).
37: Capital Sewer System (rooms 3700-3799).
38: Capital Sewer System II (rooms 3800-3899).
39: Haven (rooms 3900-3999).
40: Mines of Moria (rooms 4000-4099).
41: Mines of Moria (rooms 4100-4199).
42: Dragon Chasm (rooms 4200-4299).
43: Arctic Zone (rooms 4300-4399).
44: Orc Camp (rooms 4400-4499).
45: Woodland Monastery (rooms 4500-4599).
46: Ant Hill (rooms 4600-4699).
50: Great Eastern Desert (rooms 5000-5099).
51: Drow City (rooms 5100-5199).
52: City of Thalos (rooms 5200-5299).
53: Great Pyramid (rooms 5300-5399).
54: New Thalos (rooms 5400-5499).
55: New Thalos II (rooms 5500-5599).
56: New Thalos Wilderness (rooms 5600-5699).
57: Zodiac (rooms 5700-5799).
60: Haon-Dor, Light Forest (rooms 6000-6099).
61: Haon-Dor, Light Forest II (rooms 6100-6199).
62: Orc Enclave (rooms 6200-6299).
63: Arachnos (rooms 6300-6399).
64: Rand's Tower (rooms 6400-6499).
65: Dwarven Kingdom (rooms 6500-6599).
70: Sewer, First Level (rooms 7000-7099).
71: Second Sewer (rooms 7100-7199).
72: Sewer Maze (rooms 7200-7299).
73: Tunnels in the Sewer (rooms 7300-7399).
74: Newbie Graveyard (rooms 7400-7499).
75: Zamba (rooms 7500-7599).
78: Gideon (rooms 7800-7899).
79: Redferne's Residence (rooms 7900-7999).
83: Glumgold's Sea (rooms 8300-8399).
86: Duke Kalithorn's Keep (rooms 8600-8699).
90: Oasis (rooms 9000-9099).
96: Domiae (rooms 9600-9699).
100: Northern Highway (rooms 10000-10099).
101: South Road (rooms 10100-10199).
103: DBZ World (rooms 10300-10399).
104: Land of Orchan (rooms 10400-10499).
106: Elcardo (rooms 10600-10699).
107: Realms of Iuel (rooms 10700-10799).
115: Monestary Omega (rooms 11500-11599).
117: Los Torres (rooms 11700-11799).
118: The Dollhouse (rooms 11800-11899).
120: Rome (rooms 12000-12099).
125: Hannah (rooms 12500-12599).
130: Mist Maze (rooms 13000-13099).
140: Wyvern City (rooms 14000-14099).
150: King Welmar's Castle (rooms 15000-15099).
169: Gibberling Caves (rooms 16900-16999).
175: Cardinal Wizards (rooms 17500-17599).
186: Newbie Zone (rooms 18600-18699).
187: Circus (rooms 18700-18799).
200: Western Highway (rooms 20000-20099).
201: Sapphire Islands (rooms 20100-20199).
211: Tarot (rooms 21100-21199).
220: The Enchanted Kitchen (rooms 22000-22099).
232: Terringham (rooms 23200-23299).
233: Dragon Plains (rooms 23300-23399).
234: Newbie School (rooms 23400-23499).
235: Dwarven Mines (rooms 23500-23599).
236: Aldin (rooms 23600-23699).
237: Dwarven Trade Route (rooms 23700-23799).
238: Crystal Castle (rooms 23800-23899).
239: South Pass (rooms 23900-23999).
240: Dun Maura (rooms 24000-24099).
241: Starship Enterprise (rooms 24100-24199).
242: New Southern Midgaard (rooms 24200-24299).
243: Snowy Valley (rooms 24300-24399).
244: Cooland Prison (rooms 24400-24499).
245: The Nether (rooms 24500-24599).
246: The Nether II (rooms 24600-24699).
247: Graveyard (rooms 24700-24799).
248: Elven Woods (rooms 24800-24899).
249: Jedi Clan House (rooms 24900-24999).
250: DragonSpyre (rooms 25000-25099).
251: Ape Village (rooms 25100-25199).
252: Castle of the Vampyre (rooms 25200-25299).
253: Windmill (rooms 25300-25399).
254: Mordecai's Village (rooms 25400-25499).
255: Shipwreck (rooms 25500-25599).
256: Lord's Keep (rooms 25600-25699).
257: Jareth Main City (rooms 25700-25799).
258: Light Forest (rooms 25800-25899).
259: Haunted Mansion (rooms 25900-25999).
260: Grasslands (rooms 26000-26099).
261: Inna & Igor's Castle (rooms 26100-26199).
262: Forest Trails (rooms 26200-26299).
263: Farmlands (rooms 26300-26399).
264: Banshide (rooms 26400-26499).
265: Beach & Lighthouse (rooms 26500-26599).
266: Realm of Lord Ankou (rooms 26600-26699).
267: Vice Island (rooms 26700-26799).
268: Vice Island II (rooms 26800-26899).
269: Southern Desert (rooms 26900-26999).
270: Wasteland (rooms 27000-27099).
271: Sundhaven (rooms 27100-27199).
272: Sundhaven II (rooms 27200-27299).
273: Space Station Alpha (rooms 27300-27399).
274: Adria: Saint Brigid (rooms 27400-27499).
275: New Sparta (rooms 27500-27599).
276: New Sparta II (rooms 27600-27699).
277: Shire (rooms 27700-27799).
278: Oceania (rooms 27800-27899).
279: Notre Dame (rooms 27900-27999).
280: Living Motherboard (rooms 28000-28099).
281: Forest of Khanjar (rooms 28100-28199).
282: Infernal Pit of Kerjim (rooms 28200-28299).
283: Haunted House (rooms 28300-28399).
284: Ghenna (rooms 28400-28499).
285: Descent to Hell II (rooms 28500-28599).
286: Descent to Hell (rooms 28600-28699).
287: Ofingia and the Goblin Town (rooms 28700-28799).
288: Galaxy (rooms 28800-28899).
289: Werith's Wayhouse (rooms 28900-28999).
290: Lizard Lair Safari (rooms 29000-29099).
291: Black Forest (rooms 29100-29199).
292: Kerofk (rooms 29200-29299).
293: Kerofk II (rooms 29300-29399).
294: Trade Road (rooms 29400-29499).
295: Jungle (rooms 29500-29599).
296: Froboz Fun Factory (rooms 29600-29699).
298: Castle of Desire (rooms 29800-29899).
299: Abandoned Cathedral (rooms 29900-29999).
300: Ancalador (rooms 30000-30099).
301: Campus (rooms 30100-30199).
302: Campus II (rooms 30200-30299).
303: Campus III (rooms 30300-30399).
304: Temple of the Bull (rooms 30400-30499).
305: Chessboard (rooms 30500-30599).
306: Newbie Tree (rooms 30600-30699).
307: Castle (rooms 30700-30799).
308: Baron Cailveh (rooms 30800-30899).
309: Keep of Baron Westlawn (rooms 30900-30999).
310: Graye Area (rooms 31000-31099).
311: The Dragon's Teeth (rooms 31100-31199).
312: Leper Island (rooms 31200-31299).
313: Farmlands of Ofingia (rooms 31300-31399).
314: X'Raantra's Altar of Sacrifice (rooms 31400-31499).
315: McGintey Business District (rooms 31500-31599).
316: McGintey Guild Area (rooms 31600-31699).
317: Wharf (rooms 31700-31799).
318: Dock Area (rooms 31800-31899).
319: Yllythad Sea (rooms 31900-31999).
320: Yllythad Sea II (rooms 32000-32099).
321: Yllythad Sea III (rooms 32100-32199).
322: McGintey Bay (rooms 32200-32299).
323: Caverns of the Pale Man (rooms 32300-32399).
324: Army Encampment (rooms 32400-32499).
325: Revelry (rooms 32500-32599).
326: Army Perimeter (rooms 32600-32699).
343: God Complex  (rooms 34300-34399).
345: Asylum for the Insane (rooms 34500-34599).
346: God Hall Ext 346 for God Hall Cmplx (rooms 34600-34699).
555: Ultima (rooms 55500-55599).
556: Ultima II (rooms 55600-55699).
653: Apartment (rooms 65300-65399).
654: Subdivision (rooms 65400-65499).

**Comment by welcor** [comment]
Well, it's actually _in the game_ - the areas command shows them.
Also, it's in the help file: https://github.com/tbamud/tbamud/blob/master/lib/text/help/help.hlp#L13273 (though this may be a little outdated - I haven't compared it to your list)
