### ISSUE TITLE
Server reporting SYSERR

### ISSUE THREAD

**Issue by tjr1974** [tbamud/tbamud#107]
Upon starting the server all appears to be functioning as it should. However once a character has logged on, we get: 
SYSERR: the wandering spirit (#1202): Attempting to call non-existing mob function.

![Screenshot from 2022-10-18 09-25-06](https://user-images.githubusercontent.com/116045172/196472930-1a556a5c-3828-4485-85c8-d8e2d9ba4238.png)

This may help point to the cause. After deleting mob 1202, we get:
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #343, line 50
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #343, line 83
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #343, line 103
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #343, line 108
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #343, line 229
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #343, line 232
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #343, line 235
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #343, line 237
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #346, line 7
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #346, line 44
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #346, line 55
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #346, line 60
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #346, line 93
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #346, line 98
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #346, line 103
Oct 18 09:27:52 2022 :: SYSERR: zone file: Invalid vnum 1202, cmd disabled
Oct 18 09:27:52 2022 :: SYSERR: ...offending cmd: 'M' cmd in zone #346, line 104

It appears the offending culprit is the script(s) located in file(s) 343.trig and or 346.trg

**Comment by welcor** [comment]
I can't seem to reproduce this one:
```
thomas@thomas-c-ubuntu:~/code$ git clone https://github.com/tbamud/tbamud.git tbamud2
Cloning into 'tbamud2'...
remote: Enumerating objects: 9911, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9911 (delta 0), reused 4 (delta 0), pack-reused 9904
Receiving objects: 100% (9911/9911), 11.50 MiB | 7.09 MiB/s, done.
Resolving deltas: 100% (7160/7160), done.
thomas@thomas-c-ubuntu:~/code$ cd tbamud2
thomas@thomas-c-ubuntu:~/code/tbamud2$ ./configure >/dev/null
thomas@thomas-c-ubuntu:~/code/tbamud2$ cd src
thomas@thomas-c-ubuntu:~/code/tbamud2/src$ make .accepted

TbaMUD is freeware (it doesn't cost anything), but it is copyrighted
and has a license.  You must read and agree to abide by the license before
using tbaMUD.

This message will only appear once (the first time you compile the server),
but is contained in the file doc/license.txt if you'd like to refer back to
it in the future.

Press return to read the license. Press Q to ACCEPT the terms and quit.
 

Press return or Q to ACCEPT the terms of this license.
Press Control-C if you DO NOT ACCEPT the terms of this license.

thomas@thomas-c-ubuntu:~/code/tbamud2/src$ make >/dev/null
thomas@thomas-c-ubuntu:~/code/tbamud2/src$ cd ..
thomas@thomas-c-ubuntu:~/code/tbamud2$ bin/circle 9090
No etc/config file, using defaults: No such file or directory
Using file descriptor for logging.
Oct 18 23:28:34 2022 :: Loading configuration.
Oct 18 23:28:34 2022 :: tbaMUD 2021
...
Oct 18 23:28:34 2022 :: Resetting #653: Apartment (rooms 65300-65399).
Oct 18 23:28:34 2022 :: Resetting #654: Subdivision (rooms 65400-65499).
Oct 18 23:28:34 2022 :: Boot db -- DONE.
Oct 18 23:28:34 2022 :: Signal trapping.
Oct 18 23:28:34 2022 :: Entering game loop.
Oct 18 23:28:34 2022 :: No connections.  Going to sleep.
Oct 18 23:28:38 2022 :: New connection.  Waking up.
Oct 18 23:28:51 2022 :: Welcor [localhost] new player.
Oct 18 23:28:52 2022 :: Error opening last_file for reading, will create.
Oct 18 23:28:53 2022 :: Welcor had no variable file
Oct 18 23:28:53 2022 :: Welcor entering game with no equipment.
Oct 18 23:29:12 2022 :: Welcor has quit the game.
Oct 18 23:29:13 2022 :: Losing player: Welcor.
Oct 18 23:29:13 2022 :: No connections.  Going to sleep.
Oct 18 23:29:15 2022 :: New connection.  Waking up.
Oct 18 23:29:28 2022 :: Foo [localhost] new player.
Oct 18 23:29:30 2022 :: Foo had no variable file
Oct 18 23:29:30 2022 :: Foo entering game with no equipment.
^COct 18 23:29:54 2022 :: SYSERR: Received SIGHUP, SIGINT, or SIGTERM.  Shutting down...

```
As you can see, I don't see the problem you are having.

**Comment by tjr1974** [comment]
This was completely my fault! I replaced the code in the do_auto_exits function with the code from the ACMD(do_exits) function. For some reason, this causes the server to report each time a trigger script causes some mob to change rooms.

There are no errors in the trigger scripts for that mob. Near as I can determine, these are simply notifications, not errors. Removing the scripts eliminates the issue. I'll have to investigate more to determine why the replacement do_auto_exits code causes the server to monitor and report mob movement caused by trigger scripts.
