### ISSUE TITLE
Server reporting SCRIPT ERROR

### ISSUE THREAD

**Issue by tjr1974** [tbamud/tbamud#108]
Upon starting the server all appears to be functioning as it should. However once a character has logged on, we get:
SCRIPT ERROR: Room 55571 :: wdoor: invalid direction
I suspect this is caused by trigger 55569 in conjuntion with a bad door vnum.

![Screenshot from 2022-10-18 09-25-06](https://user-images.githubusercontent.com/116045172/196474130-398f24c9-ea59-4177-be2f-21d512c66344.png)

**Comment by welcor** [comment]
As I commented on #107 I'm not seeing this error. Which version are you using?

**Comment by tjr1974** [comment]
This was completely my fault! I replaced the code in the do_auto_exits function with the code from the ACMD(do_exits) function. For some reason, this causes the server to report:
  SCRIPT ERROR: Room 55577 :: wdoor: invalid direction
  SCRIPT ERROR: Room 55618 :: wdoor: invalid direction
  SCRIPT ERROR: Room 55624 :: wdoor: invalid direction
  SCRIPT ERROR: Room 55569 :: wdoor: invalid direction
  SCRIPT ERROR: Mob (Hazel, the wellmaster, VNum 109):: mdoor: invalid direction
There are no errors in the trigger scripts for those rooms or that mob. Near as I can determine, this replacement do_auto_exits function causes the server to report exit links (to rooms) being reassigned by trigger scripts and doors being opened or closed by trigger scripts. These are simply notifications, not errors.

Near as I can determine, there's no actual problem here. Although, these notifications are annoying and unnecessary. Removing the scripts eliminates the issue. I'll have to investigate more to determine why the replacement do_auto_exits code causes the server to monitor and report changes in the state of exits caused by trigger scripts.
