### ISSUE TITLE
Maps for tbaMUD

### ISSUE THREAD

**Issue by rds1983** [tbamud/tbamud#129]
Hello,
I am dev of [MUDMapBuilder](https://github.com/rds1983/MUDMapBuilder), which is utility to generate map images for a MUD's areas.
I've tested the utility on the tbaMUD and generated a map for almost every area. The resulting pack of maps(187 maps) could be downloaded here: [tbaMUD_Areas.zip](https://github.com/rds1983/MUDMapBuilder/releases/download/0.1.5/tbaMUD_Areas.zip)
Hopefully it could be useful.

**Comment by rds1983** [comment]
Moved generated tbaMUD maps along with its eqlist there: https://mudmapbuilder.github.io/

**Comment by welcor** [comment]
I'll add it to the doc :)
