### ISSUE TITLE
DG script freeze mud

### ISSUE THREAD

**Issue by bylins** [tbamud/tbamud#135]
script
while 1
  while 0
  done
done
freeze mud, need terminate.
problem where 
dg_scripts.cpp line 2582 
Best regards, Stribog.

**Comment by welcor** [comment]
Thanks for the bug report. I guess this happens because there's not actually implemented a stack, so a nested while causes the automatic breaking of loops to trip up. I'll look into it.

**Comment by bylins** [comment]
it's inconvenient for me to understand the solution from the commit text, but I just removed the loops reset here.
the fact is that it should be reset every event after wait 1 as it reaches 30. I'll download your code and see what you get, there are a lot of differences with us.

**Comment by bylins** [comment]
At first glance, the solution is working, I just wanted to make my own loops counter for a separate while, although this is also not without drawbacks. I'll try it at bylins

**Comment by welcor** [comment]
The solution just makes nested while loops have separate counters. The problem was that the common `loops` variable was reset on the `while 0` call. In practice this solution will use 4 extra bytes for each script line. This should not be felt in ordinary operation.

**Comment by bylins** [comment]
In general, the ideology of the patch is wrong.
Wasted memory, the fact is that in line 2605 process_wait(go, trig, type, "wait 1", cl);
after the end of wait in EVENT(trig_wait_event), we run script_driver(go, trig, type, TRIG_WAIT);
the loops variable has been reset.  It was enough to remove the zeroing of loops in while false. So creating a separate element in cmdlist of 4 bytes per line that eats up memory is definitely wrong. I don't know about you, we have 16755 triggers.

**Comment by welcor** [comment]
Thanks for the input. :)
