### ISSUE TITLE
Issues with float 2.01

### ISSUE THREAD

**Issue by elijah-z142** [tbamud/tbamud#57]
The code printf("%lf", 2.001) results in "2.100000" being printed. This seems to be an issue with the leading zeros, as "2.101" does not have issue.

Here is a possible solution:
```
    // count digits
    long digitsTmp = fracpart;
    int digits = 0;
    while (digitsTmp > 0){
        digitsTmp = digitsTmp/10;
        digits++;
    }

    /* Convert fractional part */
    do {
        fconvert[fplace++] =
                (caps? "0123456789ABCDEF":"0123456789abcdef")[fracpart % 10];
        fracpart = (fracpart / 10);
    } while(fracpart && (fplace < 20));
    // Add missing digits
    if(digits > 0){
      for(int di=digits;di<max;di++){
          fconvert[fplace++] = '0';
      }
    }
    if (fplace == 20)
        fplace--;
    fconvert[fplace] = 0;
```

There is a need to count the number of digits and to add to fconvert/fplace zeros for the missing digits.

**Comment by zlangley** [comment]
`%ld` is the placeholder for a long int. For a floating point, use `%f`.

**Comment by elijah-z142** [comment]
Edited. The bug is not related to the size of the float.

**Comment by toddcarnes** [comment]
I don't think that was his point.  The point is you should not expect the
code snippet you posted to work properly when you are asking your program
to print an int, but you're actually supplying a float.

An int will drop the fractional part of your floating point number.

**Comment by elijah-z142** [comment]
I must have used %lf and typed %ld for the issue tracker.

**Comment by zlangley** [comment]
What exactly is the issue you're seeing? Are you suggesting that the `printf` function from the standard library is not working correctly?

**Comment by elijah-z142** [comment]
I've made a few modifications to get the code to run outside of "tbamud", which is why I did not post exact code. Just ignore that about printf. The unit tests (#define TEST_SNPRINTF 1) pass, however if you add to "int_fmt" list in main (src/bsd-snprintf.c) the number 2.01 exactly, then it will not pass.

The result will be:

> snprintf doesn't match Format: %-1.5f
> 	snprintf = 2.10000
> 	sprintf  = 2.01000
> snprintf doesn't match Format: %1.5f
> 	snprintf = 2.10000
> 	sprintf  = 2.01000
> snprintf doesn't match Format: %123.9f
> 	snprintf =                                                                                                                 2.100000000
> 	sprintf  =                                                                                                                 2.010000000
> snprintf doesn't match Format: %10.5f
> 	snprintf =    2.10000
> 	sprintf  =    2.01000
> snprintf doesn't match Format: % 10.5f
> 	snprintf =    2.10000
> 	sprintf  =    2.01000
> snprintf doesn't match Format: %+22.9f
> 	snprintf =           +2.100000000
> 	sprintf  =           +2.010000000
> snprintf doesn't match Format: %+4.9f
> 	snprintf = +2.100000000
> 	sprintf  = +2.010000000
> snprintf doesn't match Format: %01.3f
> 	snprintf = 2.100
> 	sprintf  = 2.010
> snprintf doesn't match Format: %4f
> 	snprintf = 2.100000
> 	sprintf  = 2.010000
> snprintf doesn't match Format: %3.2f
> 	snprintf = 2.10
> 	sprintf  = 2.01
> 10 tests failed out of 176.

In all of your test cases, you are testing number like (fractionally):
99/100 = .99
90/100 = .90 (actually no tests with a zero on the right, but this works)
901/1000 = .901
1/10 = 0.1

They all fit the pattern of numbers whose # of digits without zero padding is equal to the max digits for their place. If you add any number with left zeros ex.
1/100 = .01
1/1000 = 0.001
2/100 = 0.02
etc

Then it fails to add the padding for whatever reason.
