### ISSUE TITLE
Change Website Downloads link to Github

### ISSUE THREAD

**Issue by kosmoit** [tbamud/tbamud#59]
https://www.tbamud.com/ Download Now Link points to Google Drive.  Could someone kindly explain the reasoning for this, and if it has been proposed to point people to github instead?

**Comment by OpieDelivers** [comment]
Apologies for the delay. 

Link in the website is for the official version released. GitHub is a work in progress during an entire year until we do the actual official release for that year. 

We will look into adding the GitHub link to the site and make sure we make a note explaining this.
