### ISSUE TITLE
little bug, and confusion

### ISSUE THREAD

**Issue by Rescator7** [tbamud/tbamud#78]
goto girl
cast 'charm' girl
stat girl

will show: 
...

> Master is: Castillo, Followers are: <none>
>AFF: CHARM 
>SPL: (110hr) charm person          
>Triggers:
> None.

but, it should show this:
>Master is: Castillo, Followers are: <none>
>AFF: CHARM 
>SPL: (110hr) charm person          sets CHARM, 
>Triggers:
> None.

This is because of confusion that 
NUM_AFF_FLAGS is 22, and not 23

either, NUM_AFF_FLAGS should be 23, or some codes should be changed like

from act.wizard.c 
 if (aff->modifier)
          send_to_char(ch, ", ");
        for (i=0; i<NUM_AFF_FLAGS; i++) {
          if (IS_SET_AR(aff->bitvector, i)) {
            send_to_char(ch, "sets %s, ", affected_bits[i]);
          }
        }

to for (i=1; i<=NUM_AFF_FLAGS; i++) {

===============================================================
grep NUM_AFF_FLAGS *

act.wizard.c:        for (i=0; i<NUM_AFF_FLAGS; i++) {
dg_variables.c:              if (check_flags_by_name_ar(GET_OBJ_AFFECT(o), NUM_AFF_FLAGS, subfield, affected_bits) == TRUE)
magic.c:      for (j=0; j<NUM_AFF_FLAGS; j++) {
medit.c:  column_list(d->character, 0, affected_bits + 1, NUM_AFF_FLAGS, TRUE);
medit.c:    else if (i <= NUM_AFF_FLAGS)
oedit.c:  for (counter = 1; counter < NUM_AFF_FLAGS; counter++) {
oedit.c:    if (number > 0 && number <= NUM_AFF_FLAGS) {
players.c:        if (num5 > 0 && num5 <= NUM_AFF_FLAGS)  /* Ignore invalid values */
structs.h:#define NUM_AFF_FLAGS   22

Bob

**Comment by welcor** [comment]
Yep, inconsistent usage here. 

I think perhaps I'll need to fix other similar issues at the same time.
