### ISSUE TITLE
circle option -c crash

### ISSUE THREAD

**Issue by Rescator7** [tbamud/tbamud#81]
The circle option -c Enable syntax check mode crash.

gdb --args bin/circle -c
Starting program: /home/rescator/MUD/FRESH/tbamud/bin/circle -c
No etc/config file, using defaults: No such file or directory
Syntax check mode enabled.
Using file descriptor for logging.
Feb 21 15:44:33 2020 :: Loading configuration.
Feb 21 15:44:33 2020 :: tbaMUD 2020
Feb 21 15:44:33 2020 :: Using lib as data directory.
Feb 21 15:44:33 2020 :: Loading zone table.
Feb 21 15:44:33 2020 ::    189 zones, 13608 bytes.
Feb 21 15:44:33 2020 :: Loading triggers and generating index.
Feb 21 15:44:33 2020 :: Loading rooms.
Feb 21 15:44:33 2020 ::    12732 rooms, 2342688 bytes.
Feb 21 15:44:33 2020 :: Renumbering rooms.
Feb 21 15:44:33 2020 :: Checking start rooms.
Feb 21 15:44:33 2020 :: Loading mobs and generating index.
Feb 21 15:44:33 2020 ::    3705 mobs, 118560 bytes in index, 2134080 bytes in prototypes.
Feb 21 15:44:33 2020 :: Loading objs and generating index.
Feb 21 15:44:33 2020 ::    4765 objs, 152480 bytes in index, 1143600 bytes in prototypes.
Feb 21 15:44:33 2020 :: Renumbering zone table.
Feb 21 15:44:33 2020 :: Loading shops.
Feb 21 15:44:33 2020 :: Loading quests.
Feb 21 15:44:33 2020 ::    1 entries, 128 bytes.
Feb 21 15:44:33 2020 :: Clearing game world.

Program received signal SIGSEGV, Segmentation fault.
queue_free (q=0x0) at dg_event.c:327
327	    for (qe = q->head[i]; qe; qe = next_qe) 
(gdb)

**Comment by welcor** [comment]
Interesting. At least it should be an easy fix - it's an obvious null pointer.
