### ISSUE TITLE
Dropping multiple gold should not create multiple stacks

### ISSUE THREAD

**Issue by welcor** [tbamud/tbamud#86]
Sapphire wrote:

>  One thing I'm also considering because it was brought up among my administration team is the wait state included in the drop_gold function within act.item.c. This is totally separate from the purge issue, but I was tinkering with gold coin drops and realized that each separate instance of a coin drop produces its own in-room pile of gold rather than combining. With Cedit it's possible to stack them, but they never actually combine. It just seems like strange behavior considering a mort with 1,000,000 coins can produce 1,000,000 instances of gold piles if they are given enough time.

Castillo replied:

> (35) One miserable gold coin is lying here.
> Stacking look good, but if each coins is having an object structures it use memory. Reaching 100k, or 1M should takes lot of times, though.
> 
> What looks bad is when you get all:
> 18H 100M 84V (news) (motd) > get all
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> You get a gold coin.
> There was 1 coin.
> 
> 
> I don't know. Making a unique coins pile per room that combine shouldn't be too hard,
> but is that what it should be?
> This code is not perfect !
> 
> It just to give an idea of what a unique stack of coins could be.
> In fact, instead of a double extract_obj, and create_money. There should probably be
> an update_room_coins function.
> 
> Also, if you cast 'invisibility' on the stack on ground, after that if you kill a mobile. Once the corpse decay. The money will sums up and become visible.
> 
> This is just a quick 11 lines example.
> 

```
void obj_to_room(struct obj_data *object, room_rnum room)
{
+  struct obj_data *obj_room, *coins;

  if (!object || room == NOWHERE || room > top_of_world)
    log("SYSERR: Illegal value(s) passed to obj_to_room. (Room #%d/%d, obj %p)",
        room, top_of_world, (void *)object);
  else {
+    if (GET_OBJ_TYPE(object) == ITEM_MONEY) {
+      for (obj_room = world[room].contents; obj_room; obj_room = obj_room->next_content)
+         if (GET_OBJ_TYPE(obj_room) == ITEM_MONEY) {
+           coins = create_money(GET_OBJ_COST(obj_room) + GET_OBJ_COST(object));
+           extract_obj(obj_room);
+           extract_obj(object);
+           object = coins;
+           break;
+         }
+    }
    object->next_content = world[room].contents;
    world[room].contents = object;
    IN_ROOM(object) = room;
    object->carried_by = NULL;
    if (ROOM_FLAGGED(room, ROOM_HOUSE))
      SET_BIT_AR(ROOM_FLAGS(room), ROOM_HOUSE_CRASH);
  }
```

**Comment by welcor** [comment]
I'm little bit worried about breaking backwards compatibility here. Some world-builders have explicitly created money piles with different names and containing different amounts in their worlds. That would not work with the example code.

**Comment by Rescator7** [comment]
An other idea i had was when you get all.  To sums the coins, and count how many pile there was, and says: You got 1240 coins from 5 piles of coins.

Also, maybe their should have a limit of coins piles maybe? There is no reasons to have let's says 100 differents coins piles.

**Comment by dwburke** [comment]
This seems like a nit-pick you should change in your own copy of the code if you dislike the current behavior.  Or implement it as a config flag and submit a PR so users can optionally change or keep it as is, then tbamud can have a default they are comfortable with.  (I'm not affiliated with tbamud, I like to watch the repo for changes and discussions so I don't know if they would be receptive to such a PR, it's just an idea).

**Comment by Rescator7** [comment]
Obviously, this isn't a crash issue. Where a fix is needed. Unless, doing drop 1 coin and using a BOT to repeat 100,000 times and "get all" crash the game?!? I'm not even going to test that theory. I'm only making suggestions. To help Sapphire, and make TBAmud better. Of course, a cedit option to turn on/off a new behavior is not a bad idea. This is all up to tbamud developper to decide what to do, or keeps it as it is. (status quo)

**Comment by welcor** [comment]
After some serious testing (it takes a while to drop ~10k coins), it's obvious that we'll hit the overflow before disconnection.

```
Test gets a gold coin.
Test gets a gold coin.
Test gets a gold coin.
Test gets a gold coin.
Test gets a gol**OVERFLOW**
```
This makes this a cosmetic issue - I agree with @dwburke - it's up to an implementor to fix this themselves if it bothers them. Marking as wontfix.
